#!/usr/bin/env python3
"""
update_schema.py
────────────────────────────────────────────────────────────────────────────────
Reads common_schema.json and injects the updated schema into App.jsx,
replacing the COMMON_SCHEMA constant automatically.

Usage (run from the frontend project root):
    python update_schema.py

Both files are expected to sit alongside this script, OR you can override
the paths using the two constants at the top of the file.
────────────────────────────────────────────────────────────────────────────────
"""

import json
import re
import sys
import shutil
from datetime import datetime
from services.common_paths import DATA_DIR, PROJECT_ROOT

# ── CONFIGURE PATHS HERE IF NEEDED ───────────────────────────────────────────
# By default the script looks for both files in the same folder as itself.

SCHEMA_JSON_PATH = DATA_DIR / "common_schema.json"   # ← source of truth
APP_JSX_PATH     = PROJECT_ROOT / "frontend" / "src" / "App.jsx"      # ← file to update
BACKUP_ENABLED   = True                                 # keeps App.jsx.bak before every update

# ── FIELD FILTER (same logic as the React app) ────────────────────────────────
# Fields whose names contain non-ASCII characters or characters other than
# letters, digits and underscore are silently dropped from the catalogue —
# they cannot be used as clean JSON property keys.

def is_clean_field_name(name: str) -> bool:
    return name.isascii() and all(c.isalnum() or c == "_" for c in name)

# ── JSON → JS CONVERSION ──────────────────────────────────────────────────────
# JSON is valid JavaScript when used as an expression, so we simply pretty-print
# the JSON and wrap it with  const COMMON_SCHEMA = …;
# The React app reads this object at runtime — it does not care whether keys
# are quoted or not.

def build_js_block(schema: dict) -> str:
    """Return the full  const COMMON_SCHEMA = { … };  replacement block."""

    # Rebuild properties with only clean field names
    raw_properties = schema.get("properties", {})
    clean_properties = {k: v for k, v in raw_properties.items() if is_clean_field_name(k)}
    filtered_count = len(raw_properties) - len(clean_properties)

    schema_to_embed = dict(schema)           # shallow copy so we don't mutate the original
    schema_to_embed["properties"] = clean_properties

    json_str = json.dumps(schema_to_embed, indent=2, ensure_ascii=False)

    header = (
        "// ─────────────────────────────────────────────────────────────────────────────\n"
        "// SCHEMA  —  auto-generated by update_schema.py\n"
        f"// Source : common_schema.json\n"
        f"// Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"// Fields : {len(clean_properties)} catalogue fields "
        f"({filtered_count} Hebrew/special-char fields excluded)\n"
        f"// Ifaces : {len(schema.get('$defs', {}))} interfaces, "
        f"{len(schema.get('allOf', []))} allOf routing branches\n"
        "// ─────────────────────────────────────────────────────────────────────────────\n"
    )

    return f"{header}const COMMON_SCHEMA = {json_str};"


# ── REPLACEMENT LOGIC ─────────────────────────────────────────────────────────
# The script finds the block that starts with  const COMMON_SCHEMA =  and ends
# at the first  };  that closes it (brace-counting), then swaps in the new block.

def replace_common_schema_block(jsx_text: str, new_block: str) -> str:
    """
    Find  const COMMON_SCHEMA = { … };  in jsx_text (handles any indentation /
    formatting) and replace it with new_block.  Raises ValueError if not found.
    """

    # Find the start line
    start_match = re.search(r'^(const COMMON_SCHEMA\s*=\s*\{)', jsx_text, re.MULTILINE)
    if not start_match:
        raise ValueError(
            "Could not find 'const COMMON_SCHEMA = {' in App.jsx.\n"
            "Make sure the constant is defined exactly like that (no export, no let/var)."
        )

    start_pos = start_match.start()

    # Walk forward counting braces until the block closes
    depth = 0
    end_pos = None
    in_string = False
    string_char = None
    i = start_match.start(1)          # start at the opening brace position

    while i < len(jsx_text):
        ch = jsx_text[i]

        # Track string literals so braces inside strings are ignored
        if in_string:
            if ch == "\\" :            # escape sequence — skip next char
                i += 2
                continue
            if ch == string_char:
                in_string = False
        else:
            if ch in ('"', "'", "`"):
                in_string = True
                string_char = ch
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    # We want to include the  };  that follows the closing brace
                    # Consume optional whitespace + semicolon
                    end_pos = i + 1
                    if end_pos < len(jsx_text) and jsx_text[end_pos] == ";":
                        end_pos += 1
                    break
        i += 1

    if end_pos is None:
        raise ValueError(
            "Found 'const COMMON_SCHEMA = {' but could not locate the matching '};\n"
            "The file may have unbalanced braces."
        )

    return jsx_text[:start_pos] + new_block + jsx_text[end_pos:]


# ── MAIN ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  update_schema.py — WMS Validator schema sync")
    print("=" * 60)

    # 1. Read common_schema.json
    if not SCHEMA_JSON_PATH.exists():
        sys.exit(f"\n❌  Schema file not found:\n    {SCHEMA_JSON_PATH}\n"
                  "    Set SCHEMA_JSON_PATH at the top of this script.")
    with open(SCHEMA_JSON_PATH, encoding="utf-8") as f:
        schema = json.load(f)
    print(f"\n✅  Loaded  {SCHEMA_JSON_PATH.name}")
    print(f"    {len(schema.get('properties', {}))} total properties, "
          f"{len(schema.get('$defs', {}))} interfaces, "
          f"{len(schema.get('allOf', []))} routing branches")

    # 2. Read App.jsx
    if not APP_JSX_PATH.exists():
        sys.exit(f"\n❌  App.jsx not found:\n    {APP_JSX_PATH}\n"
                  "    Set APP_JSX_PATH at the top of this script.")
    original_jsx = APP_JSX_PATH.read_text(encoding="utf-8")
    print(f"\n✅  Loaded  {APP_JSX_PATH}")
    print(f"    {original_jsx.count(chr(10))+1} lines")

    # 3. Backup App.jsx
    if BACKUP_ENABLED:
        backup_path = APP_JSX_PATH.with_suffix(".jsx.bak")
        shutil.copy2(APP_JSX_PATH, backup_path)
        print(f"\n💾  Backup saved → {backup_path.name}")

    # 4. Build the replacement JS block
    new_block = build_js_block(schema)
    clean_count = len([k for k in schema.get("properties", {}) if is_clean_field_name(k)])
    filtered    = len(schema.get("properties", {})) - clean_count
    print(f"\n🔧  Built new COMMON_SCHEMA block")
    print(f"    {clean_count} fields included, {filtered} excluded (Hebrew/special chars)")

    # 5. Inject into App.jsx
    try:
        updated_jsx = replace_common_schema_block(original_jsx, new_block)
    except ValueError as e:
        sys.exit(f"\n❌  {e}")

    # 6. Write the updated file
    APP_JSX_PATH.write_text(updated_jsx, encoding="utf-8")
    new_lines = updated_jsx.count(chr(10)) + 1
    print(f"\n✅  App.jsx updated  ({new_lines} lines)")

    # 7. Summary
    print("\n" + "─" * 60)
    print("  Done!  Your dev server will hot-reload automatically.")
    print("  If running in production, run:  npm run build")
    print("─" * 60 + "\n")


if __name__ == "__main__":
    main()